name: PMD Code Analysis

on:
  push:
    branches:
      - module-2-exercise

jobs:
  pmd-analysis:
    name: Run PMD Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run PMD Code Analysis
        uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'category/java/bestpractices.xml,category/java/codestyle.xml'
          version: '7.0.0-rc4'
          artifactName: 'PMD-Report'  # Changed to use hyphen instead of space